### ISSUE TITLE
Setup network ERROR!

### ISSUE THREAD

**Issue by bam80** [prusa-dev/fibocom-connect-l8x0#1]
on Megafon (didn't try others):
```
=== Fibocom Connect v2024.02.2 ===
Search modem control port DONE!
Found modem control port: COM4
Open modem control port DONE!

=== Modem information ===
Manufacturer: Fibocom
Model: L860-GL-16 LTE Module
Firmware: 18601.5001.00.01.17.30_5003.14.001.012
Serial:
IMEI: ***
IMSI: ***
ICCID: ***

Initialize connection DONE!
Establish connection DONE!

=== Connection information ===
IP: 10.*.*.*
MASK: 255.0.0.0
GW: 10.69.41.221
DNS1: 10.97.52.69
DNS2: 10.97.52.77
Setup network ERROR!

Cannot process argument transformation on parameter 'ContainerId'. Cannot convert value to type System.String.
ParameterArgumentTransformationError,Get-NetworkInterface
 at <ScriptBlock>, C:\Users\Андрей\Desktop\fibocom-connect-l8x0-master\scripts\main.ps1: line 228
at Wait-Action, C:\Users\Андрей\Desktop\fibocom-connect-l8x0-master\scripts\modules\common.psm1: line 45
at <ScriptBlock>, C:\Users\Андрей\Desktop\fibocom-connect-l8x0-master\scripts\main.ps1: line 227
at <ScriptBlock>, <No file>: line 1
```
Then it repeats over and over.

Please help.

PS:
I also had to set `$COM_NAME = "*COM*"` in the script to make it find the modem.

**Comment by prusa-dev** [comment]
Скачайте последнюю версию скрипта - https://github.com/prusa-dev/fibocom-connect-l8x0/archive/refs/heads/master.zip

**Comment by bam80** [comment]
Вчера только скачивал

**Comment by prusa-dev** [comment]
Из master ветки?

**Comment by prusa-dev** [comment]
Вот этот коммит фиксит вашу ошибку - https://github.com/prusa-dev/fibocom-connect-l8x0/commit/ba34ddf8f2733eaccac6e1f8358e87e6a6a4b1d4

**Comment by bam80** [comment]
> Из master ветки?

Конечно, и коммит есть, ошибка всё равно присутствует

**Comment by prusa-dev** [comment]
Подключите модем, откройте powershell.exe и выполните команду. Только порт измените на свой от модема
```powershell
Get-PnpDevice -class ports -FriendlyName '*COM4*' -Status OK -ErrorAction SilentlyContinue | Get-PnpDeviceProperty -KeyName DEVPKEY_Device_ContainerId | Select-Object -ExpandProperty Data
```

**Comment by bam80** [comment]
С `*COM4*` продвинулось (до следующей проблемы), `*COM*` - ошибка.

**Comment by prusa-dev** [comment]
с какой целью вы указываете `*COM*` без указания номера порта? Нужно указать конкретный порт, он должен быть один.

Какая следующая проблема?

**Comment by bam80** [comment]
Я полагал что маска позволяет указывать несколько портов, из которых автоматически будет определен нужный.
Далее, нужно было определить и задать Mac адрес, этого в readme не указано

**Comment by prusa-dev** [comment]
Кто вам такое сказал?

По умолчанию ищется порт, в которjм указано acm2. У некоторых не корректно установлены драйвера и в названии отсутствует acm2, в этом случае нужно самостоятельно определить номер порта и прописать его в скрипте.

Так же номер порта нужно вручную прописать, если в системе больше одного модема L8x0.

Про MAC адрес вообще не понял, зачем что то менять? Во всех модемах он один и тот же на интерфейсе ncm1

**Comment by bam80** [comment]
Само применение маски подразумевает, что под маску может попасть более одного совпадения. Если это не так, об этом стоит явно указать в readme, вопросов не будет.

Мак у меня отличается, пока не указал свой не работало.

Что за ncm1?

**Comment by prusa-dev** [comment]
Чтобы вам понять, почему указывается в виде маски, изучите работу команды, которая используется для поиска порта
```
Get-PnpDevice -class ports -FriendlyName ...
```

ncm1 - название сетевого интерфейса, который поднимается при подключении модема.

![image](https://github.com/user-attachments/assets/a8aa2a5d-74ef-498d-899c-f1c0b909c877)

Какой у вас MAC?

**Comment by bam80** [comment]
Вероятно из-за того что можем в MBIM режиме, у него другой Мак.
Попробую в другом режиме, напишу.

Просьба указать про NCM в readme опять же. Спасибо
