### ISSUE TITLE
No connection in system

### ISSUE THREAD

**Issue by bam80** [prusa-dev/fibocom-connect-l8x0#2]
Script connects but still there is no connection in system:
```
Mobile Broadband adapter Сеть мобильной связи:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Generic Mobile Broadband Adapter
   Physical Address. . . . . . . . . : ***
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

**Comment by prusa-dev** [comment]
Читайте 4pda на мегафоне и yota почему то не работают DNS.
Пропишите в скрипте свои

**Comment by bam80** [comment]
У меня модем в режиме USB MBIM, будет он работать в таком режиме?

**Comment by prusa-dev** [comment]
Без понятия

**Comment by bam80** [comment]
В m.2 слоте могут быть разведены PCIe и/или USB шины, какие шины присутствуют у вас?

**Comment by prusa-dev** [comment]
У большинства модем работает в переходниках m2 to usb именно для этого режима работы и предназначен скрипт

**Comment by prusa-dev** [comment]
Если у вас модем работает в mbim то вам скрипт не нужен, так как винда работает в этом режиме с ним по умолчанию

**Comment by prusa-dev** [comment]
Давайте тут писать о проблемах скрипта, а не о проблемах запуска модема.

**Comment by bam80** [comment]
В том-то и дело, что в MBIM не работает.
Я его переводил в этот режим чтобы с есим встроенной работать, а сама связь не устанавливается штатными средствами.

Может в какой-то другой режим надо переключить, NCM или что там ещё?

**Comment by prusa-dev** [comment]
Скрипт предназначен для работы с модемом в NCM режиме.
В MBIM можно только метрики смотреть.

Изучите тему на 4pda - https://4pda.to/forum/index.php?showtopic=1066668&st=340#entry122921796

Еще раз, тут только о проблемах в работе скрипта.
Закрываю

**Comment by bam80** [comment]
> Скрипт предназначен для работы с модемом в NCM режиме.

Ok, напишите это в readme, пожалуйста
